name: Project auto-testing
on:
  workflow_run:
    workflows: ["Polybot Service Deployment Dev"]
    types:
      - completed

permissions: {}

jobs:
  on-success:

    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - uses: actions/checkout@v3
        with:
          sparse-checkout: .github/workflows/service-deploy-dev.yaml
      - name: Parse bot instance domain
        run: |
          sudo apt update && sudo apt install yq -y
          
          BOT_INSTANCE_DOMAIN=$(yq '.env.BOT_INSTANCE_DOMAIN' .github/workflows/service-deploy-dev.yaml)
          echo -e "\n\nParsed bot instance domain BOT_INSTANCE_DOMAIN: $BOT_INSTANCE_DOMAIN"          

          if [[ -z "$BOT_INSTANCE_DOMAIN" ]]; then
            echo -e "\n\nInvalid BOT_INSTANCE_DOMAIN env var found in .github/workflows/service-deploy-dev.yaml"
            exit 1
          fi
          
          echo "BOT_INSTANCE_DOMAIN=${BOT_INSTANCE_DOMAIN}" >> "$GITHUB_ENV"

      - name: Test Docker Compose project
        uses: appleboy/ssh-action@master
        with:
          host: ${{ env.BOT_INSTANCE_DOMAIN }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
          script: |
            
            curl -O -L https://raw.githubusercontent.com/alonitac/PolybotServiceDocker/main/test/test-compose-project.sh
            bash test-compose-project.sh

  on-failure:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    steps:
      - run: |
          echo "Your Polybot Service Deployment workflow should be completed successfully first"
          exit 1
